### ISSUE TITLE
Error uploading a gltf file

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Compressor#13]
Hello,

Based on this ticket : https://github.com/KhronosGroup/glTF-Blender-IO/issues/1979

Seems that having multiple texture data linked to the same image data index causes the error (glTF file is valid anyway, tested on glTF validator)

https://drive.google.com/file/d/1_CYZ8Qh4znf5o4m2jYcBInGJHd5lIM9X/view?usp=sharing

![image](https://github.com/KhronosGroup/glTF-Compressor/assets/1696020/e8fd1f14-534c-4db7-8bb9-53450448ed8b)

**Comment by abasilak** [comment]
Hi @julienduroure,

Does the latest commit solved your loading issue?

**Comment by julienduroure** [comment]
Seems to be ok with the file provided by original reporter @mwbeene
@mwbeene : Can you please confirm that everything is OK on your side with your workflow now?

**Comment by mwbeene** [comment]
All good now, thank you both for looking into this!
