### ISSUE TITLE
Texture with custom ICC profile are not accurately compressed

### ISSUE THREAD

**Issue by abasilak** [KhronosGroup/glTF-Compressor#15]
Tested with the _TextureEncodingTest_ sample asset.

![image](https://github.com/KhronosGroup/glTF-Compressor/assets/14894819/88b2561c-16e9-4181-b210-876156e2775c)

**Comment by ViNeek** [comment]
Commit af160e0505ca94375204a6c38dd944e75cf66d2d properly handle ICC profiles during compression
