### ISSUE TITLE
Incorrect thumbnail gamma with KTX 

### ISSUE THREAD

**Issue by echadwick-artist** [KhronosGroup/glTF-Compressor#4]
1. Download a GLB which contains KTX2 assets inside it, for example https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/samples/StainedGlassLamp/StainedGlassLamp-KTX-BasisU-Volume-ETC1S.glb 
2. Go to https://phasmatic3d.github.io/glTF-Sample-Viewer-KTX-demo/
3. Drag and drop the GLB into the 3d view.
4. Go to the Texture Compressor tab.
5. Open a new Chrome window, and repeat the above except using a GLB with PNG/JPG textures, for example  https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/samples/StainedGlassLamp/StainedGlassLamp-JPG-PNG-Volume.glb
6. Compare the two windows side-by-side.

Result: some thumbnails are displayed with incorrect gamma. 
- Normal/occlusion/rough/metal textures are overbright (they should be displayed in linear colorspace). 
- Basecolor and emissive seem to be OK.
- KTX2 with alpha channel seems to be displayed with black, compared to gray for a PNG with alpha. 

Screenshots comparing glTF with KTX vs glTF with PNG/JPG:
![2023-06-29 17_06_08-glTF Sample Viewer](https://github.com/KhronosGroup/glTF-Compressor/assets/40177036/b26218b3-ba7a-4a1f-9b5f-fca8701b9d7d)
![2023-06-29 17_11_39-AnisotropyBarnLamp gltf - Visual Studio Code](https://github.com/KhronosGroup/glTF-Compressor/assets/40177036/42b4f6e4-2fc2-4e22-a537-451656230ae6)

**Comment by abasilak** [comment]
Fixed with [#3f3daa4](https://github.com/phasmatic3d/glTF-Sample-Viewer-KTX/commit/3f3daa464d5758e59ba0b8464730f511ef2881a9)

**Comment by abasilak** [comment]
The commits https://github.com/phasmatic3d/glTF-Sample-Viewer-KTX/commit/994ec01d476c07523fdb81bced997af750a171b7 & https://github.com/phasmatic3d/glTF-Sample-Viewer-KTX/commit/0212e0c28409c72570f13c72413852ef2953012f solved this issue.

**Comment by echadwick-artist** [comment]
Looks great, thank you so much!
