### ISSUE TITLE
Anisotropy support

### ISSUE THREAD

**Issue by echadwick-artist** [KhronosGroup/glTF-Compressor#5]
glTF-Compressor seems to be using an outdated version of glTF Sample Viewer, because anisotropy is not supported here.

1. Download a GLB which uses KHR_materials_anisotropy, for example https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/AnisotropyStrengthTest/glTF-Binary/AnisotropyStrengthTest.glb
2. Go to https://phasmatic3d.github.io/glTF-Sample-Viewer-KTX-demo/
3. Drag and drop the GLB into the 3d view.

Result: Anisotropy is not being rendered. Also in the Advanced Controls tab KHR_materials_anisotropy is not shown under Disable Extensions.

![image](https://github.com/KhronosGroup/glTF-Compressor/assets/40177036/5094d552-f759-4fd5-935e-96fcb90e1e68)

**Comment by ViNeek** [comment]
Commit af160e0505ca94375204a6c38dd944e75cf66d2d added proper support for anisotropy.
