### ISSUE TITLE
Incorrect thumbnail aspect ratios with KTX

### ISSUE THREAD

**Issue by echadwick-artist** [KhronosGroup/glTF-Compressor#6]
Hi, I noticed a small problem with KTX thumbnails.

Non-square KTX textures should render their thumbnails with non-square aspect ratios, but they do not.

1. Download a GLB which contains KTX2 assets inside it, for example https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/samples/StainedGlassLamp/StainedGlassLamp-KTX-BasisU-Volume-ETC1S.glb
2. Go to https://phasmatic3d.github.io/glTF-Sample-Viewer-KTX-demo/
3. Drag and drop the GLB into the 3d view.
4. Go to the Texture Compressor tab.
5. Scroll to the end of the Texture Details list. 
6. Open a new browser window (I'm using Chrome on Windows), and repeat the above except using a GLB with PNG/JPG textures, for example https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/samples/StainedGlassLamp/StainedGlassLamp-JPG-PNG-Volume.glb
7. Compare the two windows side-by-side.

Result: non-square JPG/PNG thumbnails are shown with the correct aspect ratio, while the KTX thumbnails are always square. Non-square KTX textures should render their thumbnails with non-square aspect ratios.

![2023-07-17 16_16_20-glTF Sample Viewer with KTX](https://github.com/KhronosGroup/glTF-Compressor/assets/40177036/6bf60638-e65a-4135-a0f8-a6f9db113af4)

Thank you!

**Comment by abasilak** [comment]
The commit https://github.com/phasmatic3d/glTF-Sample-Viewer-KTX/commit/4186b1ae044cf396066c06c2d07fe2d40213abd2 solved this issue.

**Comment by echadwick-artist** [comment]
Thanks! Does [the demo app](https://phasmatic3d.github.io/glTF-Sample-Viewer-KTX-demo/) still need to be updated?

**Comment by abasilak** [comment]
Yes. We will also have to solve #2 (aspect ratio) before updating it.

**Comment by echadwick-artist** [comment]
Yay all fixed. Thank you!
