### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'checked')

### ISSUE THREAD

**Issue by Blitzy** [KhronosGroup/glTF-Compressor#7]
Having an issue running any kind of texture compression on this glb. Any time i press the 'Compress Textures' button the following error toast is shown and the following error is logged to the console. This error also occurs when I select an options from the 'Select by Type' dropdown menu.

Error toast:
![Screenshot 2023-08-11 at 9 56 31 AM](https://github.com/KhronosGroup/glTF-Compressor/assets/1583792/771c6412-7eba-40cf-a12f-5978ce508d96)

Console error:
![Screenshot 2023-08-11 at 9 56 45 AM](https://github.com/KhronosGroup/glTF-Compressor/assets/1583792/28b06d76-287e-4cab-85f4-88b3dfa6bd17)

glb:
[human_heart_3d_model_fbx_gltf.glb.zip](https://github.com/KhronosGroup/glTF-Compressor/files/12322163/human_heart_3d_model_fbx_gltf.glb.zip)

**Comment by abasilak** [comment]
Note that _Human Heart_ model includes images with ICC profiles. 
While glTF rendering ignores them (as spec suggests), compression leads to inaccurate results. 
To be solved in #15
